name: Render Cron Trigger

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render backend
        run: |
          curl -X POST https://scraper-api-j7tm.onrender.com/api/cron
